### ISSUE TITLE
Implementation notes

### ISSUE THREAD

**Issue by gbbirkisson** [enonic-cloud/app-deploy-action#1]
### Input to action

I don't like `app_src_path` and `appname`. Reasons being:
1. They dont use the same naming convention. One uses snake_case and not the other.
2. They should be optional. It is very predictable where these jars end up. This parameter does not change for 99% of people.
3. They should be merged to `app_jar` that defaults to `./build/libs/*.jar`. Having 2 causes confusion (`app_src_path` is not `src` of anything). Change the underlying logic how this is handled. See below.

### README 

These two sections in the readme called `Deploy an app over MTLS` and `Deploy an app without MTLS` are implementation details and not helpful for the average person. What are they trying to say?

### Implementation

1. The implementation should not include `- uses: actions/checkout@v2`. This action should not have to worry about that.
2. Do we really need this base64 business for the cert and key?
3. This should IMO be implemented in bash, not using pure github actions. That way its easier to debug. My suggesion would be to do something like this:

```yaml
name: 'App deploy action script'
description: 'Github action script to be used for app deployment'
inputs:
  url: 
    description: 'URL to XP instance'
    required: true
  username:  
    description: 'deploy user name'
    required: true
  password: 
    description: 'password of deploy user'
    required: true
  client_key:  
    description: 'Client key for MTLS session'
    required: false
  client_cert: 
    description: 'Client cert for MTLS session'
    required: false
  app_jar:  
    description: 'Path of the app to be deployed'
    required: true
    default: './build/libs/*.jar'

runs:
  using: "composite"
  steps:
    - name: Deploy
      env:
        XP_URL: ${{ inputs.url }}
        XP_USERNAME: ${{ inputs.username }}
        XP_PASSWORD: ${{ inputs.password }}
        CLIENT_KEY: ${{ inputs.client_key }}
        CLIENT_CERT: ${{ inputs.client_cert }}
        APP_JAR: ${{ inputs.app_jar }}
      shell: bash
      run: deploy.sh
```

And create a script called `deploy.sh`:

```bash
#!/usr/bin/env bash

# Note this is just pseudo code, I dont think its 100% correct

set -e

FILE="$(find . -wholename ${APP_JAR} | head -n 1)"

if [ -z "$FILE" ]; then
    echo "No app jar found with pattern: ${APP_JAR}"
    exit 1
else
    echo "Found app jar: ${FILE}"
fi

PARAMS="-X POST -f -s -S -o - -u ${XP_USER}:${XP_PASSWORD} -F file=@${FILE}"

if [ "$CLIENT_KEY" != "" ] && [ "$CLIENT_CERT" != "" ]; then
    echo "Using mTLS"
    KEY=$(mktemp /tmp/key.XXXXXX)
    CERT=$(mktemp /tmp/crt.XXXXXX)
    echo -n "${CLIENT_KEY}" | base64 -d > ${KEY}
    echo -n "${CLIENT_CERT}" | base64 -d > ${CERT}
    PARAMS="${PARAMS} --key ${KEY} --cert ${CERT}"
fi

curl ${PARAMS} ${XP_URL}/app/install

```

**Comment by danhul** [comment]
>  Your comments are constructive and I will make the changes. 

> Regarding the questions:

These two sections in the readme called `Deploy an app over MTLS` and `Deploy an app without MTLS` are implementation details and not helpful for the average person. What are they trying to say?
> I am thinking if the client key and cert are provided, the app deployment will go through MTLS session by authenticating the client through cert and key. If not provided, the app deployment will be without MTLS session. Isn't that the customers has to know about?

### Implementation

1. The implementation should not include `- uses: actions/checkout@v2`. This action should not have to worry about that.
> Some of the commands I run on the action couldn't execute without that, with the changes you mentioned I might not need it. 

2. Do we really need this base64 business for the cert and key?
> Client key and cert are multiple line secrets and when I used the secret in the action, it was not getting the right content. That was why I used base64 encoding.

**Comment by gbbirkisson** [comment]
> Isn't that the customers has to know about?

People using the action should know about that, true. But the README can just say something like: "If you need to authenticate using mTLS, provide a cert and a key....".  Adding the implementation details in the README is not needed. First when I read the README I though this was stuff I needed to put in my workflow. If somebody needs to know the exact curl command used, they can just read the implementations code.

> Some of the commands I run on the action couldn't execute without that.

This action we are implementing should only do 1 thing, and that is to deploy a jar. How code is checked out and build should not be of concern in this implementation. Try to keep it as simple as possible.

> When I used the secret in the action, it was not getting the right content.

Fair enough

**Comment by danhul** [comment]
@gbbirkisson I use now a shell script instead of the steps in the action. That actually makes it possible to use the client key and cert without using base64 encoding. I updated the readme accordingly.

**Comment by gbbirkisson** [comment]
Ref: https://github.com/enonic-cloud/team-cloud/issues/840

> When I tested the action with multiple .jar files under build/libs, the deployment failed and I had to make some changes.
> 1. Accept "app name" as an optional input. And the action look for that app under build/libs
>  2. If "app name" is not given as an input, the action will deploy all .jar files from build/libs one by one. I tried to set multiple files as command line arguments for the "curl" command to run ones, but it doesn't work.

> I tested this last action now in different scenarios and seems to work fine. Let me know if you have further comments/suggestions.

If you followed my suggestion above and used `app_jar` with he default `./build/libs/*.jar`. Then if you have 2 jars, you just change that param to `./build/libs/jar1.jar`. I dont understand what the problem here could be.

**Comment by danhul** [comment]
@gbbirkisson I updated the script as we agreed up on Friday. If there is no app/path input given, it looks for .jar file under ./build/libs/. If it finds only one file, the action will deploy it. If there are multiple .jar files, it informs the user to specify a single app for the action, and it stops without deploying any app.

**Comment by gbbirkisson** [comment]
I have 2 comments:

#### Nr 1
First one is about if we hit this condition in the script `More than one jar file under build/libs`:
* The script exits with code 0, indicating success. That is not good.

The current implementation has way more nested _if_ statements than needed. This makes it prone to bugs. We can implement the same logic like this:

```bash
app=`find . -wholename ${APP_JAR:-"./build/libs/*.jar"}` # Use APP_JAR if set or default to ./build/libs/*.jar
num_files=`echo "$app" | wc -w`

if [ "$num_files" != "1" ]; then
    # Failed to find just 1 file, print error and exit
    echo "This action needs exactly 1 jar but it found $num_files!"
    for a in $app; do
        echo "  $a"
    done
    
    echo "Set 'app_jar' parameter so 1 and only 1 jar is selected!"
    exit 1
else
    # We have a single jar, set it up for curl
    PARAMS="${PARAMS} -F file=@${app}"
fi

curl ${PARAMS} ${XP_URL}/app/install
```
This make for a way simpler control flow, that is in turn way easier to debug and maintain.

#### Nr 2

This one is minimal, but just makes things a bit cleaner. Instead of doing this:

```yaml
      run: |
        chmod +x ${{ github.action_path }}/deploy.sh
        bash ${{ github.action_path }}/deploy.sh
      shell: bash
```

Follow the recommendation in the [composite action docs](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) and change it to:

```yaml
      run: deploy.sh
      shell: bash
```
And also run `chmod +x deploy.sh` and push that change to `git`. The thing is that `git` remembers this `chmod` if you push it, so `deploy.sh` will then become executable by default when somebody checks out the repository.
