### ISSUE TITLE
Create action to use in github actions

### ISSUE THREAD

**Issue by gbbirkisson** [enonic-cloud/app-deploy-action#4]
Just like we have an action to deploy now: https://github.com/enonic/action-app-deploy

It would be nice if this image had an action to build everything easily.

See this repo for reference: https://github.com/justinyoo/github-actions-docker-sample/blob/master/action.yml

**Comment by rymsha** [comment]
Basically it was "done" https://github.com/enonic/enonic-ci-image/commit/53b27fdd02c51d26800d189b1db97d7c77f45403

But we would like to redo it by having GA as a tiny wrapper on enonic-ci. BTW, Github Action is capable of residing in the same repository enonic-ci-image`

**Comment by rymsha** [comment]
It is done. Need to bump to v1 and update docs

```
name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: enonic/action-app-build@v0
```
